apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-service
  name: discovery
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    app: discovery