apiVersion: v1
kind: Service
metadata:
  labels:
    app: moviecatalog-service
  name: moviecatalog
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: moviecatalog
