apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-info-service
  name: movie-info-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8082
  selector:
    app: movieinfo
