apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings-data-service
  name: ratings-data-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8083
  selector:
    app: rating
